# Generated by Django 6.0.4 on 2026-05-01 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DefaultTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')])),
                ('time_slot', models.CharField(max_length=20)),
                ('slot_number', models.PositiveSmallIntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('lesson_type', models.CharField(choices=[('lecture', 'Lecture'), ('seminar', 'Seminar'), ('lab', 'Lab')], default='lecture', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='default_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'slot_number'],
                'unique_together': {('teacher', 'day_of_week', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='ActualTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('slot_number', models.PositiveSmallIntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('group', models.CharField(max_length=100)),
                ('lesson_type', models.CharField(choices=[('lecture', 'Lecture'), ('seminar', 'Seminar'), ('lab', 'Lab')], default='lecture', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('confirmed', 'Confirmed')], default='pending', max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('dekan_note', models.TextField(blank=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='actual_entries', to=settings.AUTH_USER_MODEL)),
                ('default_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_entries', to='timetable.defaulttimetable')),
            ],
            options={
                'ordering': ['date', 'slot_number'],
                'unique_together': {('teacher', 'date', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='RedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_days_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=10)),
                ('dekan_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('dekan', models.ForeignKey(blank=True, limit_choices_to={'role': 'dekan'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_reports', to=settings.AUTH_USER_MODEL)),
                ('entries', models.ManyToManyField(related_name='reports', to='timetable.actualtimetable')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('teacher', 'week_start')},
            },
        ),
    ]
